/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProjectChart.java
 *
 * Created on Jun 3, 2011, 9:47:50 PM
 */
package gui;

import chart.Sphinx3DPieChart;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.PieDataset;
import utils.ConstantManager;

/**
 *
 * @author Ahmed Ghanem
 */
public class ProjectChart extends javax.swing.JDialog {

    private Vector projects;
    private Vector time;
    private Image mainIcon = Toolkit.getDefaultToolkit().getImage(ConstantManager.SPHNIX_ICON_PATH);

    /** Creates new form ProjectChart */
    public ProjectChart(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(mainIcon);
        setTitle(ConstantManager.SPHNIX_TITLE);

    }

    public void vectorsRef(Vector v1, Vector v2) {
        this.projects = v1;
        this.time = v2;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loading_icon.gif"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        JFileChooser savePngFile = null;
        savePngFile = new JFileChooser();
        int choice = savePngFile.showSaveDialog(savePngFile);
        if (choice == JFileChooser.CANCEL_OPTION) {
        }
        if (choice == JFileChooser.APPROVE_OPTION) {
            Sphinx3DPieChart chartCreator = null;
            chartCreator = new Sphinx3DPieChart();
            /** Create a PieDataSet* */
            PieDataset pieDataset = chartCreator.createPieDataSet(projects, time);

            /** Create 3D Pie Chart based on this dataset* */
            JFreeChart chart = chartCreator.create3DPieChart(pieDataset, ConstantManager.SPHNIX_TITLE);
            /** Define a file location to save this chart */
            String fileLocation = savePngFile.getSelectedFile().getAbsolutePath() + ConstantManager.ALLOWED_FILE_EXTENTIONS[0];

            /** Save the chart to the file system* */
            chartCreator.saveChart(chart, fileLocation);
            jLabel1.setIcon(new ImageIcon(fileLocation));

    }//GEN-LAST:event_jLabel1MouseClicked
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ProjectChart dialog = new ProjectChart(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
